// Code generated by "stringer -type ErrCode -output code_string.go -linecomment"; DO NOT EDIT.

package error

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCodeOk-0]
	_ = x[ErrCodeInvalidParams-1]
	_ = x[ErrCodeTimeout-2]
}

const _ErrCode_name = "OK无效的参数请求超时"

var _ErrCode_index = [...]uint8{0, 2, 17, 29}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
